### ISSUE TITLE
Save-Preferences: Cannot bind argument to parameter 'Preferences' because it is null.

### ISSUE THREAD

**Issue by THE-L1NUX-USER** [devblackops/Terminal-Icons#100]
![image](https://user-images.githubusercontent.com/100482403/228148269-d361314b-1a39-4e00-bf82-6e017702a22c.png)

**Comment by epenflow** [comment]
i had the same issue

**Comment by epenflow** [comment]
i've had the same issue, i dont know why last time i open terminal terminal icons run verry well but when i restart my computer i've faced this issue. any solution so far?

**Comment by THE-L1NUX-USER** [comment]
> i've had the same issue, i dont know why last time i open terminal terminal icons run verry well but when i restart my computer i've faced this issue. any solution so far?

nope didn't find any i tried installing it on another freshly installed windows machine didn't face that error in that machine.....

**Comment by epenflow** [comment]
This solved my problem  https://github.com/devblackops/Terminal-Icons/issues/99

**Comment by THE-L1NUX-USER** [comment]
Thanks fixed.

**Comment by cafetera** [comment]
Worked for me as well

Thank You
