### ISSUE TITLE
Update nerd font classes to comply with v3 changes

### ISSUE THREAD

**Issue by NewtonChutney** [devblackops/Terminal-Icons#101]
Currently the icons seem to not work with a v3 patched font.. Just noticed this behavior yesterday. See the "next release outlook" section of release 2.3.3 of the nerd-fonts repo. 

Most of the icon classes show up as deprecated in the cheat sheet, and have to change too. (eg, nf-mdi-onedrive => nf-md-microsoft_onedrive, nf-mdi-ship_wheel => nf-md-ship_wheel)

**Comment by mattcargile** [comment]
Yeah the `data\glyphs.ps1` needs a modification. I wonder if there is a way to get a `json` dump of the glyphs and name from the site.

**Comment by NewtonChutney** [comment]
> Yeah the `data\glyphs.ps1` needs a modification. I wonder if there is a way to get a `json` dump of the glyphs and name from the site.

I was able to find something useful here:
https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/glyphnames.json

From this issue: https://github.com/ryanoasis/nerd-fonts/issues/1189#issuecomment-1529995009

**Comment by Finii** [comment]
Main thread at Nerd Fonts about this issue is https://github.com/ryanoasis/nerd-fonts/issues/1190

There are tools to help migration (listed in that thread).

**Comment by jhongyu** [comment]
Is a new version planned to fix this problem?

**Comment by devblackops** [comment]
v0.11.0 has been released with support for v3 nerd fonts. Please update to that version with:

```pwsh
Update-Module Terminal-Icons
```
