### ISSUE TITLE
Some icons are not displaying properly

### ISSUE THREAD

**Issue by dennismccray** [devblackops/Terminal-Icons#103]
- Some icons are not displaying properly on Windows 11 with PowerShell 7.3.4.
- I am using the CaskaydiaCove Nerd Font 
- Terminal Icons were installed as administrator
- This is a fresh install of Windows 11 no updates 

![image](https://user-images.githubusercontent.com/101614786/236662761-9a3a59d4-b61a-495f-9c83-46fd8c9b1896.png)

![image](https://user-images.githubusercontent.com/101614786/236662864-d9af6092-1dc7-4237-bc71-b44f182b6f33.png)

![image](https://user-images.githubusercontent.com/101614786/236663034-b2696674-c739-4b05-9e2d-431cd919239f.png)

**Comment by fernandoccandidoo** [comment]
Same thing here, I formatted my pc and this problem occurred in Oh My Posh and Terminal-Icons, but in Oh My Posh I found the solution which is to run the command "oh-my-posh config migrate glyphs --write" and solved it, but for Terminal-Icons it is still the same and I did not find anything about it, only that it is a problem with Nerd Fonts 3...

![Screenshot 2023-05-07 183301](https://user-images.githubusercontent.com/61832398/236703613-b53c0880-5816-47d7-8496-89cdb3168f6f.png)

**Comment by Kuon-dev** [comment]
Refer to this issue

https://github.com/devblackops/Terminal-Icons/issues/101

I have a fork of this repo to address this issue, you can clone it if you want.

**Comment by krokofant** [comment]
@Kuon-dev Seems to work much better. Will you setup a PR?

**Comment by Kuon-dev** [comment]
> @Kuon-dev Seems to work much better. Will you setup a PR?

probably no, because I am recently pretty busy and the changes i did was a quick "urgent" hotfix that I didn't did a double check on.  I believe there are some glyphs (really small number of them) that are still not showing properly due to the icons are completely removed instead of changing from `mdi` to `md` in that fork of mine but I just don't have time to pinpoint them out.

**Comment by devblackops** [comment]
@dennismccray [v0.11.0](https://github.com/devblackops/Terminal-Icons/releases/tag/v0.11.0) has been released with support for v3 nerd fonts. Please update to that version.

```pwsh
Update-Module Terminal-Icons
```
