### ISSUE TITLE
Need an icon & color for Autodesk iLogic files..

### ISSUE THREAD

**Issue by geneb** [devblackops/Terminal-Icons#105]
Autodesk Inventor uses VB.Net for writing code extensions - these are called iLogic modules and have the extension, ".iLogicVb". 

Currently these files appear in the default (for me) light gray color and there's no custom icon associated with them.  Could you folks treat iLogic files the same as ".vb" files?  I looked for a mechanism to do this myself, but I didn't find anything that jumped out at me - I'm NOT a PowerShell programmer by any means, so it could have been completely obvious.

Thanks for your time!

**Comment by devblackops** [comment]
@geneb This has been added in https://github.com/devblackops/Terminal-Icons/commit/fb4aceebb7fb9b94bc093057dee7db3bf02c1b25. I chose the `nf-md-alpha_i` icon and #A63B22 for the color. You can search for the icon at https://www.nerdfonts.com/cheat-sheet. These made the most sense to me based on the Autodesk Inventor logo.

**Comment by geneb** [comment]
That's great, thank you!
