### ISSUE TITLE
PowerShell 7 - Required module "Configuration" is not loaded

### ISSUE THREAD

**Issue by secana** [devblackops/Terminal-Icons#11]
## Expected Behavior
After installing Terminal-Icons and importing the module in the $profile, Terminal-Icons should be loaded and work.

## Current Behavior
The following error is thrown:

```powershell
Import-Module: C:\Users\xxx\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:6
Line |
   6 |  Import-Module Terminal-Icons
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The required module 'Configuration' is not loaded. Load the module or remove the module from 'RequiredModules' in the file 'C:\Program
     | Files\WindowsPowerShell\Modules\Terminal-Icons\0.1.1\Terminal-Icons.psd1'.
```

## Steps to Reproduce (for bugs)
1. Install PowerShell 7
2. `Install-Module Terminal-Icons -Scope CurrentUser`
3. `Import-Module Terminal-Icons`

## Context
Not able to use Terminal-Icons

## Your Environment
* Module version used: 0.1.1
* Windows 10 with PowerShell 7.0.0

**Comment by devblackops** [comment]
@secana Terminal-Icons has a dependency on the [Configuration](https://www.powershellgallery.com/packages/Configuration/1.3.1) module. Can you verify that you have that module installed as well?

If you installed Terminal-Icons from PSGallery it _should_ have installed `Configuration` as well.

**Comment by secana** [comment]
@devblackops for some reason the Configuration module was not installed. Running `Install-Module Configuration` fixed it for me. Thx for the hint!
