### ISSUE TITLE
Icons not displaying correctly PS7 via Windows Terminal

### ISSUE THREAD

**Issue by Hectamus** [devblackops/Terminal-Icons#110]
I have downloaded the CaskaydiaCode nerd font. Updated the terminal and my system. With or without Atlas Engine rendering, my icons do not display as they should.

## Expected Behavior

![image](https://github.com/devblackops/Terminal-Icons/assets/73976573/7a99f4d8-62ba-4be3-a0de-54727a2e706b)
Should display something like this.

## Current Behavior

![image](https://github.com/devblackops/Terminal-Icons/assets/73976573/3dcb5d6d-c360-45b3-a9fc-c4279aeea8db)
I am getting this instead. The Nerd Font is enabled and so is Atlas Engine. Tried different variations of the nerd font and nothing works. I used to work before.

**Comment by DerTolleEmil** [comment]
The code points in the fonts have change with version 3 of the fonts. See: https://github.com/ryanoasis/nerd-fonts/issues/1190

There was a pull request to address this: #104

**Comment by devblackops** [comment]
@Hectamus Support for v3 nerd fonts has been added in [v0.11.0](https://github.com/devblackops/Terminal-Icons/releases/tag/v0.11.0). Please update to that module version with:

```pwsh
Update-Module Terminal-Icons
```

**Comment by Hectamus** [comment]
@devblackops It is working perfectly now. Thanks for the update!
