### ISSUE TITLE
[FEATURE] Add support for the .c++ and .cxx extensions for C++ files

### ISSUE THREAD

**Issue by HardoMX** [devblackops/Terminal-Icons#111]
## Expected Behavior
This would just make it so the c++ symbol also appears on .c++ and .cxx files

## Current Behavior
Right now, .cxx and .c++ files are just shown as normal files

### That was all folks, just a really short and (hopefully) simple suggestion :)

**Comment by devblackops** [comment]
Thanks @HardoMX. This has been added in 8d4ee35. It will be in the next release.
