### ISSUE TITLE
Glyphs for Jenkinsfile (already supported by nerdfonts)

### ISSUE THREAD

**Issue by Wimpzer** [devblackops/Terminal-Icons#112]
> If you have ideas for an appropriate [glyph](http://nerdfonts.com/#cheat-sheet) to display for a well-known folder or file, or a particular file extension, please raise an [issue](https://github.com/devblackops/Terminal-Icons/issues/new).

Yes, I have for Jenkinsfile.
The associated class-name from [nerd-fonts](https://www.nerdfonts.com/cheat-sheet) is "nf-dev-jenkins" or "nf-seti-jenkins".

**Comment by devblackops** [comment]
Thanks @Wimpzer. I added this in 61fdf20. It will be included in the next release.
