### ISSUE TITLE
Not all icons are being displayed correctly

### ISSUE THREAD

**Issue by valsamis-d** [devblackops/Terminal-Icons#115]
## Expected Behavior
I'm expecting to see icons for all files. I don't have any special files. Just very commons ones.

## Current Behavior
When I'm doing a _dir_ in Powershell 7 icons are not being displayed correctly for all file types. See screenshots below:

![image](https://github.com/devblackops/Terminal-Icons/assets/17590539/561294f0-20a5-41dc-b434-e3ead35d5e55)

![image](https://github.com/devblackops/Terminal-Icons/assets/17590539/82d45fd7-fc86-42d2-855b-13f4599c2527)

## Steps to Reproduce (for bugs)
1. Install _Terminal-Icons_
2. Install NF Fonts (both _CaskyadiaCove_ NF and _LiberationMono NF_.
3. Import _Terminal-Icons_ (tried with both module name and absolute path to _Terminal-Icons.psm1_)
4. _dir_ command

## Context
Nothing critical here. It's just ugly to see some files types having this nice icon and other not :)

## Your Environment
* Operating System: Windows 11 Enterprise 22H2
* PowerShell version: 7.3.6
* Windows Terminal: tried with both regular version 1.17.11461.0 and preview version 1.18.1462.0
* Module version used: 0.11.0

I also tried type _PowerShell\Modules\Terminal-Icons\0.11.0\Data\glyphs.ps1_ and indeed some icons are not being rendered correctly (see question marks):

![image](https://github.com/devblackops/Terminal-Icons/assets/17590539/1fb0a41b-ae29-40de-ba65-d60185f7c9be)

Any ideas?

EDIT:

I read through https://github.com/devblackops/Terminal-Icons/issues/99 and https://github.com/devblackops/Terminal-Icons/issues/89 but workarounds and advices offered there did not help :(

Thank you
Dimitrios

**Comment by valsamis-d** [comment]
Never mind guys. I figured it out. I was using v2 of NerdFonts. After downloading v3 eveything is working just fine and... is very sexy :)

**Comment by Tusankata** [comment]
I am experiencing the same issue. Same icons are not being recognized. Even though I have downloaded the latest nerd font patched fonts of `JetBrains Mono` and `CascaydiaCove`, downloaded from [here](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.2)

Small example inside the Terminal-Icons directory
![image](https://github.com/devblackops/Terminal-Icons/assets/47631858/b0bd2684-4ad6-4168-aa32-50202b97ae6e)

I also did what @valsamis-d suggested and ran `type glyphs.ps1`
![image](https://github.com/devblackops/Terminal-Icons/assets/47631858/13d0a880-8351-4838-86dd-bf07e110d9ac)
A small part of the glyphs that are not recognized. The ones `nf-fae-x`, `nf-fa-x`, `nf-code-x`, seem to be working, though there's an issue with the `nf-md-x` icons.

I have also ran `oh-my-posh config migrate glyphs --write`, which fixed a few of the icons and glyphs, though (as we can see) not all.

## Environment

- OS Windows 10 Pro 22H2
- PowerShell 7.3.6
- Terminal-Icons module 0.11.0

Apologies for hijacking this already closed issue. If I must, I'll open a separate one.

**Comment by valsamis-d** [comment]
@Tusankata have you installed Nerd Fonts v3.0.2 for the "current user" or "all users"? I'd suggest installing them for "all users"
