### ISSUE TITLE
No icons after installation.

### ISSUE THREAD

**Issue by Xarkam** [devblackops/Terminal-Icons#12]
## Expected Behavior
Have icons and no error raised.

## Current Behavior
No icons:
![image](https://user-images.githubusercontent.com/331816/96249960-4fa6f500-0fae-11eb-9d5e-11c04414b5fc.png)
![image](https://user-images.githubusercontent.com/331816/96250498-394d6900-0faf-11eb-82d8-2fe7ccefd867.png)
Windows Terminal config:
![image](https://user-images.githubusercontent.com/331816/96249989-62212e80-0fae-11eb-9bf9-cc65b09a2463.png)

## Steps to Reproduce (for bugs)
No idea to reproduce the bug.

## Context
Context is just in screenshot, install, load and nothing

## Your Environment

* Module version used: 0.1.1
* Operating System and PowerShell version: Windows 10 2004, Powershell Core 7.0.3

**Comment by krymtkts** [comment]
I met a same problem after I used Get-ChildItemColor.
Terminal-Icons works fine after running `Remove-Module Get-ChildItem Color`.
It seems they are incompatible.

**Comment by Xarkam** [comment]
@krymtkts thank you. It works now

**Comment by devblackops** [comment]
Good to know @krymtkts. Thanks!
