### ISSUE TITLE
Terminal icons appear only after executing a terminal-icons command

### ISSUE THREAD

**Issue by KonerDev** [devblackops/Terminal-Icons#134]
## Expected Behavior
When you run `dir` you should see the terminal icons.

## Current Behavior
When I start a new PowerShell instance and run the `dir` command, the terminal icons don't show. But when I then run the command `Show-TerminalIconsTheme` and try the `dir` command again, the terminal icons show. Am I doing something wrong or is this a bug?

## Steps to Reproduce (for bugs)

1. Start a new Powershell instance in the Windows Terminal
2. Execute `dir` => no colorful icons
3. Execute `Show-TerminalIconsTheme`
4. Execute `dir` again => colorful icons

## Your Environment

* Module version used: Terminal-Icons 0.11.0
* Operating System: Windows 11; 23H2; Build 22631.3737
* PowerShell version: 5.1.22621.3672

**Comment by meditto** [comment]
open the PowerShell profile file with a text editor
`code $profile`
and add this line
`Import-Module -Name Terminal-Icons`

**Comment by KonerDev** [comment]
Thanks, that fixes my problems. But why isn't this in the `README.md` file or did I miss something?

**Comment by meditto** [comment]
It's there in the Usage section but it's not clear
