### ISSUE TITLE
WARNING: Unable to parse prefs.xml. Setting default preferences.

### ISSUE THREAD

**Issue by schneekluth** [devblackops/Terminal-Icons#144]
When Import-Module is executed I run into a warning message:

``` ps1
Import-Module -Name Terminal-Icons

WARNING: Unable to parse [C:\Users\user\AppData\Roaming\powershell\Community\Terminal-Icons\prefs.xml]. Setting
default preferences.
Save-Preferences : Cannot process argument transformation on parameter 'Preferences'. Cannot convert the
"System.Object[]" value of type "System.Object[]" to type "System.Collections.Hashtable".
At C:\Users\user\Documents\WindowsPowerShell\Modules\Terminal-Icons\0.11.0\Terminal-Icons.psm1:3442 char:31
+ Save-Preferences -Preferences $prefs
+                               ~~~~~~
    + CategoryInfo          : InvalidData: (:) [Save-Preferences], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Save-Preferences
```

or in Powershell Core:

``` ps1
Import-Module -Name Terminal-Icons
WARNING: Unable to parse [C:\Users\user\AppData\Roaming\powershell\Community\Terminal-Icons\prefs.xml]. Setting default preferences.
Save-Preferences: Cannot process argument transformation on parameter 'Preferences'. Cannot convert the "System.Object[]" value of type
"System.Object[]" to type "System.Collections.Hashtable".
```

## Expected Behavior
Import the module without errors

## Current Behavior
This warning appears in Powershell 5.1.22621.4391:
![grafik](https://github.com/user-attachments/assets/44b0f17c-2b96-4199-ab7a-fd84322e6b8b)

This warning appears in Powershell Core 7.4.6:
![grafik](https://github.com/user-attachments/assets/d482aca9-bb93-442d-ad0d-358eca346593)

## Context
I have Terminal-Icons in my Profile and whenever a new terminal is opened the error appears.

## Your Environment

* Module version used: 0.11.0
* Operating System: Windows 11
* PowerShell version: 5.1.22621.4391
* PowerShell Core version: 7.4.6

**Comment by CheetahChrome** [comment]
I started getting this too a few days back after doing an `winget upgrade`.  I attempted to resolve by installing for the current user

`Install-Module Terminal-Icons -Scope CurrentUser`

vs my original and the standard install

`Install-Module -Name Terminal-Icons -Repository PSGallery`

which either reinstall has and no effect and produces the same error. 

Is this an issue with the latest Powershell?

**Comment by CheetahChrome** [comment]
I have reported the issue to the Powershell Feedback:

[Powershell Startup Exception Cannot convert the "System.Object[]" value of type On Startup](https://aka.ms/AAtijdb)

**Comment by CheetahChrome** [comment]
Upon looking at the prefs.xml file, it was clear it was corrupted.

**Solution**: By deleting the XML file, and a possible optional step of reinstalling to latest version of Terminal Icons...resolved the issue.

**Comment by flamfoof** [comment]
I solved it by copying the contents of devblackops_color.xml -> prefs.xml and it worked.

**Comment by schneekluth** [comment]
> Upon looking at the prefs.xml file, it was clear it was corrupted.
> 
> **Solution**: By deleting the XML file, and a possible optional step of reinstalling to latest version of Terminal Icons...resolved the issue.

The provided solution works. Thank you @CheetahChrome.
