### ISSUE TITLE
Support for Python & Java Glpyhs

### ISSUE THREAD

**Issue by manu-p-1** [devblackops/Terminal-Icons#16]
## Current Behavior
I noticed that `.py` and `.java` files were not supported yet and no glyphs were present for their file types. Could these be added? Enhancement proposal would have been posted below, however, the glyphs don't render properly.

![image](https://user-images.githubusercontent.com/28782438/100535170-67e07580-31e4-11eb-8b24-39c7dee32685.png)

## Expected Behavior
The correct glyphs should appear next to the appropriate file type

## Possible Solution
Add the following glyphs to the existing theme set

1. For Python: https://www.nerdfonts.com/cheat-sheet
2. For Java: https://www.nerdfonts.com/cheat-sheet

**Comment by devblackops** [comment]
@manu-p-1 Python and Java have been added in #17

**Comment by manu-p-1** [comment]
> @manu-p-1 Python and Java have been added in #17

@devblackops Awesome! Looks good!

**Comment by devblackops** [comment]
Cool. Published as `0.2.1`. https://www.powershellgallery.com/packages/Terminal-Icons/0.2.1

Thanks for the issue!
