### ISSUE TITLE
Display targets for reparse points (junctions, links, etc.)

### ISSUE THREAD

**Issue by cklutz** [devblackops/Terminal-Icons#19]
Display targets for reparse points (junctions, links, etc.)

## Expected Behavior

It would be helpful if "reparse points" (junction, sym links on Windows, sym links on Unix)
would be display their "target" in `Get-ChildItem` "default" output.

```
PS C:\> dir C:\temp\dummy

        Directory: C:\temp\dummy


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d----        06.10.2020     15:14                  target
l----        13.01.2021     13:20                  link -> C:\temp\dummy\target
```

## Current Behavior

```
PS C:\> dir C:\temp\dummy

        Directory: C:\temp\dummy


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d----        06.10.2020     15:14                  target
l----        13.01.2021     13:20                  link
```

While you can (subtly) see that an entry is a link, not a real directory (by the Mode "l"), you cannot easily see the target of the link,
requiring manual PS-foo like ` Get-ChildItem  | Select-Object Mode, LastWriteTime, Length, Name, Target | Format-Table`. While
that works, it does not honor the icons.

## Possible Solution

In http://github.com/cklutz/Terminal-Icons I have created a fork that provides the above capability by modifying `Format-TerminalIcons.ps1`
slightly:

```
diff --git a/Terminal-Icons/Public/Format-TerminalIcons.ps1 b/Terminal-Icons/Public/Format-TerminalIcons.ps1
index 982b8b2..2de8a9d 100644
--- a/Terminal-Icons/Public/Format-TerminalIcons.ps1
+++ b/Terminal-Icons/Public/Format-TerminalIcons.ps1
@@ -35,6 +35,10 @@ function Format-TerminalIcons {
         $escape      = [char]27
         $colorReset  = "${escape}[0m"
         $displayInfo = Resolve-Icon $FileInfo
-        "$($displayInfo.Color)$($displayInfo.Icon)  $($FileInfo.Name)$colorReset"
+        $targetInfo  = ''
+        if ($FileInfo.Attributes -band [System.IO.FileAttributes]::ReparsePoint) {
+            $targetInfo = ' -> ' + $FileInfo.Target
+        }
+        "$($displayInfo.Color)$($displayInfo.Icon)  $($FileInfo.Name)$targetInfo$colorReset"
     }
 }
```

This issue (and a possible PR) would only address the most basic addition, like just adding the `-> Target`
to the output. It generally also be feasible to have a custom icon for reparsepoints. But this I have not
addressed.

## Steps to Reproduce (for bugs)

See "Current Behavior"

## Context

Better usability when working with links and junctions. For example, our software typically is installed as 
`PRODNAME-VERSION`  (e.g. `ABC-1.3.10`) and we create a link to the most current version during
installation, keeping the old ones. That results in a directory like this:

ABC-1.3.10
ABC-1.3.9
ABC-1.20
ABC-CURRENT

`ABC-CURRENT` is the name that the configuration and software uses. Without the above change it
is pretty cumbersome to figure out what it "points" to.

I'm sure there are other use cases as well as links are even on Windows no longer a stepchild.

## Your Environment

* Module version used: 0.2.2
* Operating System and PowerShell version: Windows 10, PowerShell 7.1.0

**Comment by devblackops** [comment]
This is good idea @cklutz. I have an implementation in #21.

**Comment by cklutz** [comment]
Cool! Thanks. :-)
