### ISSUE TITLE
Consider adding versions with ligatures

### ISSUE THREAD

**Issue by paulomorgado** [devblackops/Terminal-Icons#24]
I prefer `Cascadia Mono` over `Cascadia Code` because I want to see the characters that need to be typed, not a pretty painting of text.

**Comment by devblackops** [comment]
Ligatures are a function of the nerd font being used. Terminal-Icons doesn't do anything with ligatures by itself. If you'd prefer not use ligatures, there are nerd fonts that don't have them.
