### ISSUE TITLE
File name not shown

### ISSUE THREAD

**Issue by zanseb** [devblackops/Terminal-Icons#25]
## Expected Behavior
The name of a file should always be displayed, even if the extension of the file could not be matched to a specific icon/pattern.

## Current Behavior
It seems that files without file extension are not displayed at all. However, special files like "LICENSE" are displayed nonetheless.

![image](https://user-images.githubusercontent.com/8336867/114193758-2066b480-994f-11eb-9785-89a97c7d5b5f.png)
![image](https://user-images.githubusercontent.com/8336867/114193888-3e341980-994f-11eb-9572-4b550171a57f.png)

## Your Environment

* Module version used: 0.3.0
* Operating System and PowerShell version: Win10 20H2, PowerShell 7

**Comment by zanseb** [comment]
I think the main problem is that https://github.com/devblackops/Terminal-Icons/blob/master/Terminal-Icons/Data/colorThemes/devblackops.psd1 has no entry for "no extension ('')". This leads to the problem that the modules tries to retrieve a substring with -1 in https://github.com/devblackops/Terminal-Icons/blob/ff89838a860da6fbccf9d5c573ef13ba73ae9dce/Terminal-Icons/Private/Resolve-Icon.ps1#L72.

**Comment by devblackops** [comment]
@zanseb Yep. Good catch.

**Comment by devblackops** [comment]
`0.3.1` has been [published](https://www.powershellgallery.com/packages/Terminal-Icons/0.3.1). Thanks for the fix @zanseb
