### ISSUE TITLE
Can't add color theme

### ISSUE THREAD

**Issue by cdhunt** [devblackops/Terminal-Icons#28]
Receive a number of these errors trying to `Add-TerminalIconsColorTheme`. The theme is based on the default theme with `Name` and 3 color changes.

```powershell
InvalidOperation: C:\source\github\Terminal-Icons\Terminal-Icons\Private\Add-Theme.ps1:63
Line |
  63 |  …             $script:colorSequences[$item.BaseName].Types.Files[$_.Nam …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot index into a null array.
```

It looks like it goes to build `$script:colorSequences[$item.BaseName]` but `$script:colorSequences[$item.BaseName]` is empty where `$item.BaseName` is the new color theme I'm trying to add.

**Comment by devblackops** [comment]
Theme support is...not the greatest yet and needs to be refactored a bit.

**Comment by MJECloud** [comment]
@devblackops @cdhunt I think i [fixed](https://github.com/MJECloud/Terminal-Icons/commit/d7b508dc6591ba5f3a781dbb0f201cc2bee83c21#diff-cf295563d5d32b05172c3757f4a89e98cf03f5b72906bec3c517f8a3c2b7770e) it.

Maybe have a look first and test it yourself? :)

**Comment by devblackops** [comment]
Theming (and a bunch of other stuff) has been refactored in [this](https://github.com/devblackops/Terminal-Icons/tree/theming-refactor) branch. 

To test, you can run `.\build.ps1 build && ipmo .\Output\Terminal-Icons\0.4.0\Terminal-Icons.psd1`

**Comment by MJECloud** [comment]
It works like a charm, thanks!

**Comment by cdhunt** [comment]
Confirmed.
