### ISSUE TITLE
File named "SConstruct" has blank for icon and filename

### ISSUE THREAD

**Issue by MiMiMeowMeow** [devblackops/Terminal-Icons#29]
I have a file named "SConstruct" has blank for icon and filename when i'm expecting at least the file icon and the file name.

## Steps to Reproduce (for bugs)
1.  I have posh-git and Terminal-Icons installed
2.  Create a file called SConstruct
3.  view the directory listing 

Windows 10, PowerShell version 5.1.19041.906
Just installed Terminal-Icons module today.

![image](https://user-images.githubusercontent.com/12488828/114236214-256b3a00-9936-11eb-99c1-94336a5670ca.png)

**Comment by devblackops** [comment]
Thanks for the issue @MiMiMeowMeow. This is the same issue as https://github.com/devblackops/Terminal-Icons/issues/25 and has been fixed in https://github.com/devblackops/Terminal-Icons/pull/26. It will be in the next version.

**Comment by devblackops** [comment]
@MiMiMeowMeow `0.3.1` has been [published](https://www.powershellgallery.com/packages/Terminal-Icons/0.3.1) which should resolve this. Please update to that version.

**Comment by MiMiMeowMeow** [comment]
Pickup up 0.3.1 and tested.  Works now.  Thanks!!!
Awesome work BTW.
