### ISSUE TITLE
Glyphs are not rendered correctly

### ISSUE THREAD

**Issue by mu88** [devblackops/Terminal-Icons#31]
![2021-04-12_08h57_15](https://user-images.githubusercontent.com/4560672/114353437-4ec1db00-9b6d-11eb-8b4e-f384a81bb683.png)

## Expected Behavior

The glyphs are rendered correctly in Windows Terminal.

## Current Behavior

It seems that the glyphs are not recognized at all in Windows Terminal. I have both `FiraCode Nerd Font` and `Caskaydia Cove Nerd Font` installed and these fonts do successfully work in VS Code, Rider and Visual Studio.

## Steps to Reproduce (for bugs)

0. I had both `FiraCode Nerd Font` and `Caskaydia Cove Nerd Font` installed, as well as *Oh my Posh 3*.
1. I've installed `Terminal-Icons` via `Install-Module -Name Terminal-Icons -Repository PSGallery`
2. I've added the new module to my profile `$profile`: `Import-Module -Name Terminal-Icons`
3. Restart of complete machine

## Your Environment
- Module version used: I guess `0.3.0` - I've executed `Install-Module -Name Terminal-Icons -Repository PSGallery`
- Operating System and PowerShell version:
  - Windows 10 Version 1909, OS Build 18363.1440
  - PowerShell Core 7.1.3
  -  Windows Terminal 1.6.10571.0

**Comment by Tiberriver256** [comment]
What do you have your default fontFace value set to in your settings.json file for Windows Terminal?

![image](https://user-images.githubusercontent.com/6989492/114394225-f5f04380-9b68-11eb-86b7-fb5680ac1a43.png)

Mine for example:
![image](https://user-images.githubusercontent.com/6989492/114394278-056f8c80-9b69-11eb-895d-b29d8b38ddd7.png)

**Comment by mu88** [comment]
It is set to `Fira Code`
![image](https://user-images.githubusercontent.com/4560672/114394576-a5dea480-9b9b-11eb-83c3-536293e48416.png)

**Comment by Tiberriver256** [comment]
So you probably just need to change that to the Nerd Font equivalent. Fira Code by itself doesn't have the same glyphs that Fira Code Nerd Font will.

Depending on how you installed the font it may be either **Fira Code Nerd Font** or just **Fira Code NF**. I believe Windows Terminal will pick up changes to the settings.json automatically every time you hit save, so you should just be able to change it and hit save until you can see the glyphs rendered.

**Comment by mu88** [comment]
Oh I didn't know that Fira Code and Fira Code Nerd Font differ - good to know!

After setting the font face to `FiraCode NF`, it is working like a charm. Thank you for your help 👌🏻
