### ISSUE TITLE
Icons not displayed in windows terminal

### ISSUE THREAD

**Issue by jsacapdev** [devblackops/Terminal-Icons#32]
## Expected Behavior

On my local machine, I would expect to see this in the windows terminal:

![image](https://user-images.githubusercontent.com/10151920/114563989-d1c75c00-9c67-11eb-89c2-7ef9ca1b5fb5.png)

Which is what I see if I use Windows PowerShell

## Current Behavior

On the terminal, the icons are missing, as shown below:

![image](https://user-images.githubusercontent.com/10151920/114564193-03402780-9c68-11eb-8650-7f2a038403b9.png)

Notice the icons are just squares

## Steps to Reproduce (for bugs)

1.  `Install-Module -Name Terminal-Icons -Repository PSGallery`
2. `code $profile`
3. Add the following into the file `Microsoft.PowerShell_profile.ps1`:
``` pwsh
Import-Module posh-git
Import-Module oh-my-posh
Import-Module -Name Terminal-Icons
```
4. Open Windows Terminal

## Context

If it is useful, this is what my terminal settings look like:

``` json
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
    "initialCols": 130,
    "initialRows": 30,
    "multiLinePasteWarning": false,
    "profiles": {
        "defaults": {
            "fontFace": "Courier New"
        },
        "list": [
            {
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "name": "PowerShell",
                "fontFace": "Courier New",
                "source": "Windows.Terminal.PowershellCore"
            }
        ]
    }
}
```

## Your Environment

* Module version used: `0.3.1`
* Operating System and PowerShell version: Windows 10 (Azure VM). `PowerShell 7.1.3`

**Comment by devblackops** [comment]
@jsacapdev Terminal-Icons **requires** a nerd font to be used because the font is what includes the glyphs to display. You have it set to `Courier New`. Can you set it to whatever nerd don't you have set in your other terminal?

**Comment by jsacapdev** [comment]
@devblackops that worked. thank you.

**Comment by dubeyravivinod** [comment]
I have tried all the steps, still no icons are showing.
![image](https://user-images.githubusercontent.com/116741133/198861861-322ef1eb-793e-4eba-a572-4c11db1d34e6.png)

**Comment by safeblood** [comment]
some problem

**Comment by Sisyphus141** [comment]
I'm using powershell7. After setting up everything and installing nerd font you need to go to powershell7 in the profile you are using you need to change the default font.

**Comment by ifli87** [comment]
Hi, im havint the same problem but only for when i run the PowerShell in the VisualStudio, dosent get the icons even tho i done all the steps, and have the right font, any advice?

**Comment by kl3ssydra** [comment]
> I have tried all the steps, still no icons are showing. ![image](https://user-images.githubusercontent.com/116741133/198861861-322ef1eb-793e-4eba-a572-4c11db1d34e6.png)

you must change ur terminal font

i use Cascadia Code SemiLight of nerdfonts

**Comment by Sisyphus141** [comment]
In powershell7, in settings under the terminal you set up go to appearance then change "font face" to one of the nerd font. If you have done that I would also recommend running this command >> Install-Module -Name Terminal-Icons -Repository PSGallery

**Comment by safeblood** [comment]
> > I have tried all the steps, still no icons are showing. ![image](https://user-images.githubusercontent.com/116741133/198861861-322ef1eb-793e-4eba-a572-4c11db1d34e6.png)
> 
> you must change ur terminal font
> 
> i use Cascadia Code SemiLight of nerdfonts

i change the font but the still malfunction

**Comment by AbdullahSaidAbdeaaziz** [comment]
@ifli87 you should should apply font (`shows icons`) you in your in vscode terminal also (go to setting vscode -> search for font of terminal and apply your font in font-family field). that work for me.

**Comment by developer-shajib** [comment]
( Import-Module posh-git
Import-Module oh-my-posh
Import-Module -Name Terminal-Icons )

Your All Step I did perfectly. But when I past this code Microsoft.PowerShell_profile.ps1 file then show and error.

#[https://ibb.co/Qdw4MJm](url)

[https://ibb.co/Ptn3X1Q](url)

**Comment by CheetahChrome** [comment]
What worked for me was uninstalling Terminal via 

`winget uninstall Microsoft.WindowsTerminal`

then in a normie powershell window, because Terminal magically goes away, I installed it

`winget install Microsoft.WindowsTerminal`

then in Terminal Settings->Defaults->Appearance is set to my font of choice

`CaskaydiaCove Nerd Font`

and started a new shell and I could see the directory icons. 

---

My guess is at onetime I had the Terminal Preview installed or I am running on the Dev ring of Windows Update and something got horked.
