### ISSUE TITLE
Import Terminal-Icons Module on Ubuntu

### ISSUE THREAD

**Issue by lennybacon** [devblackops/Terminal-Icons#36]
I tried to get terminal icon running on ubuntu 20. I installed the module successfully.
Then I typed `Import-Module -Name Terminal-Icons` 

## Expected Behavior
Terminal icons module is loaded

## Current Behavior

When not running under `sudo`, which provides no output, I get the following error message:
```
New-Item: /usr/local/share/powershell/Modules/Terminal-Icons/0.5.0/Terminal-Icons.psm1:186
Line |
 186 |              New-Item -Path $storagePath -ItemType Directory -Force >  …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Access to the path '/etc/xdg/xdg-ubuntu/powershell/Community'
     | is denied.
```

## Steps to Reproduce (for bugs)
1. Install Ubuntu 20.04
2. Install PowerShell 7.1.7
3. Start `pwsh`
4. Run `Install-Module -Name Terminal-Icons -Repository PSGallery`
4. Run `Import-Module -Name Terminal-Icons` 

## Your Environment
* Module version used: 0.5.0
* Operating System and PowerShell version: Ubuntu 20.04 and PowerShell 7.1.7

**Comment by devblackops** [comment]
Hi @lennybacon, what value(s) do you have for `$env:XDG_CONFIG_DIRS`?

**Comment by devblackops** [comment]
Actually, come to think of it, I think the default location for storing user theme files should be under `($env:XDG_CONFIG_HOME/.local/share` (if it exists), and then fallback to `$HOME/.local/share` if `$env:XDG_CONFIG_HOME` is not present.

**Comment by devblackops** [comment]
@lennybacon This should be fixed in https://github.com/devblackops/Terminal-Icons/commit/eeb5ce85d4a1882b5155bd6f06859a4b6f4b44d8

**Comment by lennybacon** [comment]
@devblackops Thanks a lot. I am quite busy and haven't had the time to send you my values of `$env:XDG_CONFIG_DIRS`. Super cool you worked on the topic! 🤩

If I should upate and test smth let me know

**Comment by devblackops** [comment]
@lennybacon v0.5.1 has been [released](https://www.powershellgallery.com/packages/Terminal-Icons/0.5.1) that should fix this.

**Comment by lennybacon** [comment]
@devblackops It does. Great - Thanks a lot!
