### ISSUE TITLE
Add Visual Studio Solution filter file extension (.slnf)

### ISSUE THREAD

**Issue by kkoziarski** [devblackops/Terminal-Icons#38]
## Expected Behavior
Showing `nf-dev-visualstudio` icon for `.slnf` files.

## Current Behavior
`.slnf` files are not handled and default icon is displayed

## Possible Solution
In `devblackops.psd1` add line:
```
'.slnf' = 'nf-dev-visualstudio'
```

## Context
Handling and displaying proper icon for `.slnf` files.

**Comment by devblackops** [comment]
[0.5.2](https://www.powershellgallery.com/packages/Terminal-Icons/0.5.2) Includes these changes. Thanks!
