### ISSUE TITLE
Minimum required version is too low for .Where()

### ISSUE THREAD

**Issue by potatoqualitee** [devblackops/Terminal-Icons#4]
PSv3 is listed in Gallery but I just saw some `.Where()` syntax which is only supported in PSv4 and above.

**Comment by devblackops** [comment]
Thank's for catching that. I'm going to bump the minimum to PSv4.

**Comment by devblackops** [comment]
This is fixed in 3d7b8f8b07297577236202e8c31dcf8e1c6d7f5f. The minimum PS version is now v4.
