### ISSUE TITLE
Suggesting more icons

### ISSUE THREAD

**Issue by KaranKad** [devblackops/Terminal-Icons#42]
## Expected Behavior

![image](https://user-images.githubusercontent.com/71691514/127703034-2d67962d-39e7-4130-afaf-648f9856adbf.png)

## Current Behavior

These folders and files have no icons, also `.img` format needs different icon shown in expected behavior.
![image](https://user-images.githubusercontent.com/71691514/127702871-edb320d2-9088-4230-871a-dee45a143fa8.png)

## Possible Solution

You can check these changes at my fork https://github.com/KaranKad/Terminal-Icons/tree/newicons
If you like these changes, I am ready to submit pull request. 
## Context

I have replaced `nf-dev-java` with `nf-fae-java` because it scales better when zooming in.

## Your Environment

* Module version used: 0.5.2
* Operating System and PowerShell version: Windows 10 21H1 and PowerShell 7.1.3

**Comment by devblackops** [comment]
Hi @KaranKad. These look great. Please submit the PR!
