### ISSUE TITLE
Escape characters appear when the result is piped to less

### ISSUE THREAD

**Issue by comiluv** [devblackops/Terminal-Icons#43]
## Expected Behavior
All icons and colors are properly displayed

## Current Behavior
```gci | format-list | less```
<img width="591" alt="화면 캡처 2021-08-11 112744" src="https://user-images.githubusercontent.com/19642705/128960294-91d7d3b1-253b-4760-8b43-3884d88cef1b.png">

## Possible Solution
As a workaround, can be piped to more and icons are displayed rather correctly
```gci | format-list | more```
<img width="591" alt="화면 캡처 2021-08-11 112910" src="https://user-images.githubusercontent.com/19642705/128960404-df4faf32-eac5-4a85-b16b-d36644ffa224.png">

## Steps to Reproduce (for bugs)
1. Get-ChildItem | Format-List | less

## Context
I want to pipe everything to less

## Your Environment

* Module version used: 0.5.2
* Operating System and PowerShell version: Windows 10 19043.1110, Powershell 7.1.3

**Comment by devblackops** [comment]
@comiluv Are you using this less version? https://github.com/jftuga/less-Windows

**Comment by comiluv** [comment]
I'm actually using one from [chocolatey](https://community.chocolatey.org/packages/Less) but looks like those are identical versions. I suppose I'll close the issue now as it's issue with less
