### ISSUE TITLE
Would it possible to skip the icons and use just the colors?

### ISSUE THREAD

**Issue by DavidZidar** [devblackops/Terminal-Icons#46]
I know this module is literally called Terminal-Icons but I really like the color theme, it is much better than PoshColor, and I don't want any icons.

## Expected Behavior
It would be nice if it was possible to set the icon theme property to empty string or $null to disable the icons and get just the colors.

## Current Behavior
I have been unable to figure out how to get rid of the icons.

## Possible Solution
I have tried to create an empty icon theme but I'm getting icons anyway, but I have not spent a lot of time on this.

## Your Environment
* Module version used: 0.5.2
* Operating System and PowerShell version: Windows 10, PowerShell 7.1.4

**Comment by DavidZidar** [comment]
The reason I don't want the icons is because my favorite font, Fira Code, does not support them. I tried the patched nerd font-version (several of the variants) but for some reason they look like a blurry unreadable mess in Windows Terminal so that is not an option.

**Comment by devblackops** [comment]
Thanks for the issue @DavidZidar. You right, it's not possible (currently) to disable the icon theme. I'll look at how best to do that.

**Comment by devblackops** [comment]
@DavidZidar This commit should do it. https://github.com/devblackops/Terminal-Icons/commit/1985be702575be16489a0413f7430bbf5bb45e79. You can now disable icons or colors (or both) with the new  `-DisableIconTheme` and `-DisableColorTheme` switches on `Set-TerminalIconsTheme`

![image](https://user-images.githubusercontent.com/12634452/132633040-2c1235ed-4ce6-41eb-ab96-18e319893e96.png)

**Comment by DavidZidar** [comment]
@devblackops That's awesome, the disable switches makes more sense than passing in null or empty string as I suggested, looks great. Thank you! I am unsure how to test this so I'll eagerly await the next release.

**Comment by SharakPL** [comment]
@devblackops do you plan to release new version with this feature anytime soon?

**Comment by devblackops** [comment]
@DavidZidar @SharakPL v0.6.0 has been released with this addition. Sorry for the delay in publshing!

https://www.powershellgallery.com/packages/Terminal-Icons/0.6.0

**Comment by DavidZidar** [comment]
@devblackops Just tried it, works great, I love it.. thank you!

**Comment by SharakPL** [comment]
Great addition! I don't use Nerd Font as it makes every single glyph little off compared to original (not to mention it's not updated as frequently as required) and names with  ◻ squares everywhere were kinda pointless.

Thanks 🎉
