### ISSUE TITLE
Importing Terminal-Icons is not successful 

### ISSUE THREAD

**Issue by TheGamer20131** [devblackops/Terminal-Icons#47]
When Improting the Terminal-Icons Module i get the error message as seen in the screenshot.

## Expected Behavior
The Module should Import without errors

## Current Behavior
The module doesn't load correctly

I already tryed reinstalling the Module multiple times.

![image](https://user-images.githubusercontent.com/29305070/132137247-5c88c1cd-f192-44a0-8dd0-0499954bd712.png)

## Your Environment
* Module version used:
Version 0.5.2
* Operating System and PowerShell version:

Windows 10
Powershell Version 5.1.19041.1151

**Comment by TheGamer20131** [comment]
Here an English Screenshot

![image](https://user-images.githubusercontent.com/29305070/132137381-5dab4012-21ef-4c14-9795-b401f9662f70.png)

**Comment by TheGamer20131** [comment]
Found my Problem. The XML files in the AppData\Roaming\powerschell\Community\Terminal-Icons somehow got corupted. Deleting them fixed my problem

**Comment by KingCheni** [comment]
Thank you.I found the same problem occurred on my powershell.Deleting these XML files can solve the problem.
