### ISSUE TITLE
OneDrive Appends Company Name To Folder Name And nf-mdi-ondrive Glyph Isn't Displayed

### ISSUE THREAD

**Issue by mattcargile** [devblackops/Terminal-Icons#49]
## Expected Behavior

Would it be reasonable to allow a wildcard so one could display the glyph icon (  `nf-mdi-onedrive` ) for a folder named `OneDrive - Business Name` for instance? Or it could just be a fix for OneDrive itself.

## Current Behavior

Currently the directory icon is the generic folder.

## Possible Solution

Not sure how to implement.

## Steps to Reproduce (for bugs)

1.OneDrive created through company. Not sure if this my employer of a OneDrive for business or the like setting.

## Context

N/A

## Your Environment

* Module version used: 0.5.2
* Operating System and PowerShell version: Windows 10 1909; Powershell Core 7.1.4

**Comment by devblackops** [comment]
@mattcargile You can create custom color and icons themes, then import them with `Add-TerminalIconsColorTheme` and `Add-TerminalIconsIconTheme` commands. Take a look at the built in ones [here](https://github.com/devblackops/Terminal-Icons/blob/main/Terminal-Icons/Data/colorThemes/devblackops.psd1) and [here](https://github.com/devblackops/Terminal-Icons/blob/main/Terminal-Icons/Data/iconThemes/devblackops.psd1).

**Comment by mattcargile** [comment]
Thanks. I eventually figured out I didn't have to generate the `xml` and I copied your `psd1` files and customized them a bit.
