### ISSUE TITLE
Missing support for .hbs Handlebars files

### ISSUE THREAD

**Issue by nikouu** [devblackops/Terminal-Icons#50]
Currently there is no .hbs file support for the Handlebars templating language. https://handlebarsjs.com/ 

## Expected Behavior

A moustache icon with an orange colouring for .hbs files.
![image](https://user-images.githubusercontent.com/983351/136348056-0dc2d38d-0223-404f-93ec-92d5587828fa.png)

 

## Current Behavior

.hbs files have no configuration and are shown using the default icon and colour.
![image](https://user-images.githubusercontent.com/983351/136348320-7cdf23be-124b-419c-9837-915d108c3eba.png)

## Possible Solution

The default Seti icon set in VS Code looks nice and would be ideal. The following is an example screenshot from VS Code:
![image](https://user-images.githubusercontent.com/983351/136349122-7229e79b-eaa0-4dbc-ba7f-baf6c612fae8.png)

## Context

I use the Handlebars and it would be great to see .hbs files styled too.

## Your Environment

* Module version used: 0.5.2
* Operating System and PowerShell version: Windows 10 and Powershell 7.1.4

**Comment by nikouu** [comment]
I have a fork ready to go https://github.com/nikouu/Terminal-Icons/tree/handlebars with the before and after looking like:
![image](https://user-images.githubusercontent.com/983351/136351115-84321d02-288c-42ae-957e-5d364edb11ad.png)

**Comment by devblackops** [comment]
@nikouu This looks good. Can you submit a PR?

**Comment by devblackops** [comment]
Thanks @nikouu. [v0.7.0](https://www.powershellgallery.com/packages/Terminal-Icons/0.7.0) has been published with these changes.
