### ISSUE TITLE
Empty Prefs.xml

### ISSUE THREAD

**Issue by IujyrinoT2** [devblackops/Terminal-Icons#56]
Script worked fine until one day I got 2 error messages when I launched my terminal: "Import-Clixml : ' . ' , hexadecimal value 0x00 is an invalid character" and "Save-Preferences : Cannot bind argument to parameter 'Preferences' because it is null"  
## Expected Behavior

If I'm running the command "Import-Module -Name Terminal-Icons" I should get no errors and the script should work fine.

## Current Behavior

When I run the command "Import-Module -Name Terminal-Icons" I get the 2 error messages mentioned above, I'll also attach an image of them.

![Screenshot 2021-11-20 083555](https://user-images.githubusercontent.com/79942888/142717913-805273e9-0754-470e-bc10-ee7e4270f27d.png)
## Possible Solution

Turns out the issue comes from the Prefs.xml file getting empty for no reason.
It may be caused by Windows 11 since my Windows 10 laptop still runs the script fine, but I'm not sure.

## Steps to Reproduce (for bugs)

1. The file Prefs.xml, located at "C:\Users\<user>\AppData\Roaming\powershell\Community\Terminal-Icons", has to be empty
2. Run the command  "Import-Module -Name Terminal-Icons"

## Context

I've been using this script for months and had no issues, even after I upgraded to Windows 11 recently. But one day when I opened the terminal I got these 2 errors. I received this error while I was on the script version 0.5.2, so I tried upgrading it to 0.7.0 but didn't work. Also tried to reinstall it afterwards. So I looked through the code at the lines from the error and found out it came from the variable $Prefs. So I looked how it is constructed and found the location of the Prefs.xml file. I checked that file on my Windows 10 laptop, where the script still works fine, and found the file populated. So I copied the contents of the file from my laptop to my desktop and now the script works.   

## Your Environment

* Module version used: 0.5.2, 0.7.0
* Operating System and PowerShell version: Windows 11, PS 5.1

**Comment by devblackops** [comment]
Thanks for the report @IujyrinoT2. I'll do some investigation about how this file could become empty. If nothing else, maybe there is some better error checking and autocorrection that can be put in.

**Comment by devblackops** [comment]
@IujyrinoT2 This should be fixed with 0296ebbca065c9b97038c6a7b945a60715080de8, which will be in the next release.
