### ISSUE TITLE
add .ipynb icon

### ISSUE THREAD

**Issue by gaardhus** [devblackops/Terminal-Icons#57]
## Expected Behavior

Thanks for a great module! I suggest that a custom icon for .ipynb files are adopted.

## Current Behavior

![image](https://user-images.githubusercontent.com/46934916/143143294-324549c7-2f85-4aad-a4e6-6bd14a9fd85a.png)

## Possible Solution

Icon: '.ipynb'                = 'nf-mdi-book'
Color: '.ipynb'                = '16c60c'

![image](https://user-images.githubusercontent.com/46934916/143143785-a3ac9f16-9bec-4d1b-a187-a2ecc80a36bd.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

It would really make it easier and more intuitive to spot the notebooks in my directories :)

## Your Environment

* Module version used:
* Operating System and PowerShell version:

**Comment by devblackops** [comment]
Sounds good @gaardhus. Do you want to submit a PR with this?

**Comment by gaardhus** [comment]
Right away @devblackops
