### ISSUE TITLE
Add icon for R language files

### ISSUE THREAD

**Issue by rumichaska** [devblackops/Terminal-Icons#62]
Hi!

I just started using Powershell and installed this awesome module. I work a lot with R scripts and I'd like if (in future versions) you can add icons for this kind of files. Locally, I added a few lines for the icon and color for R files. I couldn't find nice icons for RMarkdown (.rmd) and Rproj (.Rproj) files, so I just added what I had.

The icon I'm using (locally) for R files is 'nf-mdi-language_r' and for the color I choose '276DC2'

Thanks!

**Comment by devblackops** [comment]
Hi @rumichaska. Thanks for the issue!

R language files have been added in https://github.com/devblackops/Terminal-Icons/commit/4845cb5048e20384978de9ccd273da6d91e9e001. [v0.9.0](https://www.powershellgallery.com/packages/Terminal-Icons/0.9.0) has been released with these changes.
