### ISSUE TITLE
Add Julia Icon

### ISSUE THREAD

**Issue by jvaverka** [devblackops/Terminal-Icons#67]
Julia files ending in `.jl` should be marked with the glyph already set as `nf-seti-julia`.

## Expected Behavior
If a file named `*.jl` is in the directory then it should be accompanied with the `nf-seti-julia` glyph.

## Current Behavior
If a file named `*.jl` is in the directory then it is accompanied with the plain file glyph.

## Possible Solution
Add setting to support Julia source files.

## Your Environment
* Module version used: 0.9.0
* Operating System and PowerShell version: Windows 11 & PowerShell 7.2.1

**Comment by devblackops** [comment]
Thanks for the suggestion @jvaverka. This has been added in 3c27a64350b1080b15c68822aeb0a2e50e5d178a and will be in the next release.
