### ISSUE TITLE
Symlink and junction arrows render incorrectly

### ISSUE THREAD

**Issue by MadameMinty** [devblackops/Terminal-Icons#68]
Symlink and junction arrows render incorrectly on Windows default PowerShell (5.1.19041.1320).

## Expected Behavior
When printing directory contents on Windows Terminal, symlinks and junctions display name as "icon link-name arrow target-name".

## Current Behavior
When printing directory contents on Windows Terminal, symlinks and junctions display name as "icon link-name ï•” target-name".

![image](https://user-images.githubusercontent.com/24495074/153652348-28537c72-1fa7-4af1-9035-84077756e6be.png)

## Possible Solution
With 0.9.0, in `Terminal-Icons.psm1:312` and `Terminal-Icons.psm1:326` replace:
`$displayInfo['Target'] = '  ' + $FileInfo.Target`
with:
`$displayInfo['Target'] = ' ' + $glyphs['nf-mdi-arrow_right_thick'] + ' ' + $FileInfo.Target`

## Steps to Reproduce (for bugs)
1. Start Powershell
2. `mkdir Target`
3. `mklink /J Link Target`
4. `ls`

## Context
Arrows good. These are the only instances of explicit unicode glyphs in Terminal-Icons.psm1, so getting rid of them could be nice.

## Your Environment
* Module version used: 0.9.0
* Operating System and PowerShell version: Windows 10, Windows Terminal, PSVersion 5.1.19041.1320. This is the system default.

PSVersion 7.2.0, which is installed separately, renders the glyph correctly.

**Comment by devblackops** [comment]
Thanks @MadameMinty. This has been fixed in b022094236ecedeb38d3e2f450b984288253dde6.
