### ISSUE TITLE
Request:  Light theme

### ISSUE THREAD

**Issue by adamm1471** [devblackops/Terminal-Icons#69]
Provide a light mode (black on white) option/theme for those who don't dabble in the dark arts.

**Comment by devblackops** [comment]
@adamm0373 If you're looking for strictly black on white and not colors that would be compatible with a light theme, would disabling the colors and only showing the icons work?

```
Set-TerminalIconsTheme -DisableColorTheme
```

Example:
![image](https://user-images.githubusercontent.com/12634452/156510370-afd035d5-55dd-4322-b9ce-f6c048734220.png)

**Comment by adamm0373** [comment]
Well, it's not strictly black on white.   It'd be a shame to be rid of the colors.

**Comment by adamm1471** [comment]
how would I check it out?

**Comment by TamKengHong** [comment]
1. Download devblackops_light from my forked repo https://github.com/TamKengHong/Terminal-Icons/tree/main/Terminal-Icons/Data/colorThemes
2. Paste it into your Powershell Module Path
3. Add this to your $PROFILE:  Add-TerminalIconsColorTheme .\Documents\PowerShell\Modules\Terminal-Icons\0.9.0\Data\colorThemes\devblackops_light.psd1

**Comment by devblackops** [comment]
[v0.10.0](https://www.powershellgallery.com/packages/Terminal-Icons/0.10.0) has been released with the light theme included.

**Comment by adamm1471** [comment]
This is awesome; but I can't seem to use it using Add-TerminalIconsColorTheme; 

`   ~  Add-TerminalIconsColorTheme "C:\Program Files\WindowsPowerShell\Modules\Terminal-Icons\0.10.0\Data\colorThemes\devblackops_light.psd1"
Add-Theme : Color theme [] already exists. Use the -Force switch to overwrite.
At C:\Program Files\WindowsPowerShell\Modules\Terminal-Icons\0.10.0\Terminal-Icons.psm1:524 char:9
+         Add-Theme @PSBoundParameters -Type Color
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Add-Theme`
