### ISSUE TITLE
Terminal-Icons doesn't provide an icon for scss files

### ISSUE THREAD

**Issue by Huascar321** [devblackops/Terminal-Icons#74]
A small observation.
Terminal-icon provides an icon for *.sass files but not for *.scss

![image](https://user-images.githubusercontent.com/45210400/160530826-fa04663c-e285-495f-ba00-9073458bf5ec.png)
![image](https://user-images.githubusercontent.com/45210400/160530872-7a48ba76-6020-4966-aa45-f3799c68379a.png)

**Comment by devblackops** [comment]
@Huascar321 This has been added in https://github.com/devblackops/Terminal-Icons/commit/4fb63c4e8fae9e3d5dc50a4a218306d100dc6bfb.
