### ISSUE TITLE
VS Code terminal support?

### ISSUE THREAD

**Issue by coinzdude** [devblackops/Terminal-Icons#75]
## Expected Behavior
Should I expect terminal-icons to work, specifically the 'icons' from terminal within VS Code?

## Current Behavior
Terminal within VS code is having some issue displaying the icons, displaying rectangles instead.

![image](https://user-images.githubusercontent.com/58857646/161138902-f4935a61-0704-4e48-84be-8a8dde9586a2.png)

## Steps to Reproduce (for bugs)
have a $PROFILE with this
```
import-module -name Terminal-Icons
```

Windows 11
VS Code
Powershell 7.2.2
Terminal-Icons 0.9.0

Open VS Code and open Terminal, run 'dir'

**Comment by devblackops** [comment]
@coinzdude Yes, it works fine in VSCode. Just make sure you've installed and selected a [Nerd Font](https://www.nerdfonts.com/#home). For example, mine is set to `SauceCodePro`.

```
"editor.fontFamily": "SauceCodePro NF, 'Courier New', monospace",
```

**Comment by devblackops** [comment]
@coinzdude Did setting the font in VSCode work for you?

**Comment by coinzdude** [comment]
Thanks for checking. I did think that would do the job, and I already had the below, and Cascadia Code PL is installed.  It's a little interesting that you don't have single quotes around SauceCodePro NF there.  I'll see if I can get something to trigger.  
```
"editor.fontFamily": "'Cascadia Code PL', Jetbrains Mono, Menlo, Monaco, Consolas, 'Courier New', monospace",
```
![image](https://user-images.githubusercontent.com/58857646/163441263-9b31a469-d9e3-49ec-ba95-389945463c15.png)

**Comment by coinzdude** [comment]
I found some interesting clues as to what was wrong... 

I used this script below from here https://stackoverflow.com/questions/62458016/detect-which-font-is-in-use-by-powershell-session and got a random font back!
![image](https://user-images.githubusercontent.com/58857646/163443825-14fd1a57-9e4a-4320-ab7a-b19ed90a5a74.png)

even though, the font was set to MesloLGM NF, so I just changed my VS code terminal font manually to the same, and it works, thanks so much for the advice!

![image](https://user-images.githubusercontent.com/58857646/163444322-17847dfa-118a-4d29-92b7-958032404649.png)


```
if ( -not ('Win32test.ConsoleTest' -as [type]) ) {
$defConsoleTest = @'
using System.Runtime.InteropServices;
using System;

namespace Win32test
{
    public static class ConsoleTest
    {
        [DllImport( "kernel32.dll", 
                    CharSet = CharSet.Unicode, SetLastError = true)]
        extern static bool GetCurrentConsoleFontEx(
            IntPtr hConsoleOutput,
            bool bMaximumWindow,
            ref CONSOLE_FONT_INFOEX lpConsoleCurrentFont);

        private enum StdHandle
        {
            OutputHandle = -11  // The standard output device.
        }

        [DllImport("kernel32")]
        private static extern IntPtr GetStdHandle(StdHandle index);

        public static string GetFontCsvHeader(){
            return  "FaceName,FontFamily,FontWeight,FontSize";
        }

        public static string GetFontCsv()
        {
            // Instantiating CONSOLE_FONT_INFOEX and setting cbsize
            CONSOLE_FONT_INFOEX ConsoleFontInfo = new CONSOLE_FONT_INFOEX();
            ConsoleFontInfo.cbSize = (uint)Marshal.SizeOf(ConsoleFontInfo);

            GetCurrentConsoleFontEx( GetStdHandle(StdHandle.OutputHandle),
                                     false, 
                                     ref ConsoleFontInfo);

            return  ConsoleFontInfo.FaceName + 
              "," + ConsoleFontInfo.FontFamily + 
              "," + ConsoleFontInfo.FontWeight + 
              "," + ConsoleFontInfo.dwFontSize.X + 
                    "×" + ConsoleFontInfo.dwFontSize.Y;
        }

        [StructLayout(LayoutKind.Sequential)]
        private struct COORD
        {
            public short X;
            public short Y;

            public COORD(short x, short y)
            {
            X = x;
            Y = y;
            }
        }

        // docs.microsoft.com/en-us/windows/console/console-font-infoex
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
        private struct CONSOLE_FONT_INFOEX
        {
            public uint  cbSize;
            public uint  nFont;
            public COORD dwFontSize;
            public int   FontFamily;
            public int   FontWeight;
            [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 32)]
            public string FaceName;
        }
    }
}
'@
Add-Type -TypeDefinition $defConsoleTest
}

# convert output to a pscustomobject
[Win32test.ConsoleTest]::GetFontCsvHeader(), 
[Win32test.ConsoleTest]::GetFontCsv() |
    ConvertFrom-Csv -Delimiter ','
```
