### ISSUE TITLE
CODE_OF_CONDUCT.md returning an extra space in front of the file name

### ISSUE THREAD

**Issue by scrthq** [devblackops/Terminal-Icons#8]
When `Get-ChildItem` results contain a `CODE_OF_CONDUCT.md` file, the file name has an extra space prepended in front of it when Terminal-Icons is imported. Tested with multiple fonts, including fonts without glyphs, all come back with a space in front of that file. Also tested multiple paths.

## Expected Behavior
`CODE_OF_CONDUCT.md`'s file name is aligned with the rest of the files.

Normal output before importing Terminal-Icons:
![image](https://user-images.githubusercontent.com/12724445/63832977-8992e300-c937-11e9-8809-e5ef4e84fa7c.png)

## Current Behavior
ConEmu:
![image](https://user-images.githubusercontent.com/12724445/63832737-10938b80-c937-11e9-8b43-c6ef32e65747.png)

Terminal:
![image](https://user-images.githubusercontent.com/12724445/63832910-649e7000-c937-11e9-90d1-c93ce4d57552.png)

## Possible Solution
Remove extra space?

## Steps to Reproduce (for bugs)

1. Change location to a path with a `CODE_OF_CONDUCT.md` file in it.
2. `Get-ChildItem`

## Your Environment
```powershell
[#4] [PS 7.0.0-p3] [0:00:00.0163] [PSProfile] [dev ≡ +0 ~4 -0 !]
>> Get-Module Terminal-Icons | fl

Name              : Terminal-Icons
Path              : C:\Users\nate\Documents\PowerShell\Modules\Terminal-Icons\0.1.1\Terminal-Icons.psm1
Description       : PowerShell module to add file icons to terminal based on file extension
ModuleType        : Script
Version           : 0.1.1
PreRelease        :
NestedModules     : {}
ExportedFunctions : {Add-TerminalIconsColorTheme, Add-TerminalIconsIconTheme, Format-TerminalIcons, Get-TerminalIconsColorTheme…}
ExportedCmdlets   :
ExportedVariables :
ExportedAliases   :


[#5] [PS 7.0.0-p3] [0:00:00.0365] [PSProfile] [dev ≡ +0 ~4 -0 !]
>> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.3
PSEdition                      Core
GitCommitId                    7.0.0-preview.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by devblackops** [comment]
I think this is a bug with some of the glyphs in nerd fonts.
