### ISSUE TITLE
Slow startup with this module enabled

### ISSUE THREAD

**Issue by soredake** [devblackops/Terminal-Icons#81]
## Expected Behavior
Start faster that a second, without terminal-icons module pwsh starts in 738ms.

## Current Behavior
Starting powershell with this module took 1239ms.

## Possible Solution
I don't know.

## Steps to Reproduce (for bugs)

1. Install powershell-7 and Terminal-Icons
2. Start windows terminal with powershell-7
3. Observe a long startup

## Your Environment

* Module version used: 0.9.0
* Operating System and PowerShell version: Windows 11 Pro / PowerShell 7.2.3

**Comment by devblackops** [comment]
Thanks @soredake. I'm going to close this out because there is a discussion on improving the load time in #76.
