### ISSUE TITLE
No icon for vim files.

### ISSUE THREAD

**Issue by skhatri15** [devblackops/Terminal-Icons#82]
## Summary
I noticed I was not seeing vim file icons when listing files/directories.

## Expected Behavior
See vim icon next to .vim files in Windows Terminal (Powershell) after using the Get-ChildItem command.

## Current Behavior
Shows a white file icon instead:

![image](https://user-images.githubusercontent.com/14065821/170240273-33f85adc-266c-488b-82b9-7e44ab6667e4.png)

## Possible Solution
Adding an icon associated with the .vim filetype.

## Context
This issue is not affecting me much at all- just thought I'd point this out as a minor issue.

## Your Environment
* Module version used: 0.9.0
* Operating System and PowerShell version: Windows 10, Powershell 5.1.19041.1682

**Comment by devblackops** [comment]
@skhatri15 This has been added in https://github.com/devblackops/Terminal-Icons/commit/d7445f26b120dfdd64dc57f63e1029171d3c98b2.
