### ISSUE TITLE
Icons are Not Showing

### ISSUE THREAD

**Issue by rafay99-epic** [devblackops/Terminal-Icons#85]
## Expected Behavior
Using this Program Icons should be visiable in the terminal..

## Current Behavior
The Icons are showing up...Just a couple of boxex next to the Program name.

## Possible Solution
Please Clearly Identify the Which Fonts are required for this application...There is no documentation that will tell the user which font need to be installed.

## Steps to Reproduce (for bugs)
1. Open terminal 
2. Enter 'dir' command
3. All files will be visiable but icons next to files will not displayed but small boxes will be displayed.

## Context
We use this program to make the terminal beautiful but right now it's not beautiful.

## Your Environment
**Model:** I am using Lenovo Laptop Legion 7 Slim 
**Operating System:** I am using Window 11 Home(Curent Stable version)
**Powershell Version:** 7.2.5  Core

## ScreenShots:
![image](https://user-images.githubusercontent.com/82662797/179405035-18b886f2-8206-42bf-bd41-a9be1e20f7df.png)

**Comment by lokillo999** [comment]
did you install [nerd fonts](url https://www.nerdfonts.com/font-downloads)

**Comment by lokillo999** [comment]
Did you install [nerd fonts](https://www.nerdfonts.com/font-downloads)?

**Comment by rafay99-epic** [comment]
Brother, I installed every single nerd front from the github repo and still it did not solve the problem..
Howerver I reinstalled Window 11 and my problem was solved.
