### ISSUE TITLE
Show always icons when opening a new terminal

### ISSUE THREAD

**Issue by Sebasssssss** [devblackops/Terminal-Icons#93]
Hello, my problem is that everytime i open a new terminal or a new tab, i have to write Import-Module Terminal-Icons all over again. And i wonder if there is any way that the icons are already imported by default

**Comment by PhattaraPCRU** [comment]
@Sebasssssss  In the terminal, type "notepad $profile" and add "Import-Module -Name Terminal-Icons" before saving.

**Comment by Sebasssssss** [comment]
Hello, sorry i didn't replied. Where am i supposed the file?

**Comment by Sebasssssss** [comment]
Thank you, it worked perfectly!
