### ISSUE TITLE
Glyph request: 💪 for .bicep files

### ISSUE THREAD

**Issue by SvenAelterman** [devblackops/Terminal-Icons#94]
## Expected Behavior

Would like to see the Bicep emoji for .bicep files

## Current Behavior

Bicep files show as plain white file icons.

**Comment by devblackops** [comment]
@SvenAelterman Good idea. The closest I could find for a Bicep icon in Nerd Fonts is `nf-seti-bicep`. This looks to be a recent addition in https://github.com/ryanoasis/nerd-fonts/pull/978, so if we use this, folks need will need to update their font to a recent version that includes the updated Seti icons.

![image](https://user-images.githubusercontent.com/12634452/211476055-c5051928-78ce-4c79-a61b-d57647a4bf71.png)

**Comment by SvenAelterman** [comment]
That would be perfect! That's the same glyph that VS Code uses for the file type icon.

**Comment by devblackops** [comment]
@SvenAelterman This has been added in https://github.com/devblackops/Terminal-Icons/commit/9706edfa3895504bfb3a6c43412025b8c5d5846d

**Comment by devblackops** [comment]
@SvenAelterman [v0.11.0](https://github.com/devblackops/Terminal-Icons/releases/tag/v0.11.0) has been released with support for .bicep files.
