### ISSUE TITLE
Terminal-Icons not working

### ISSUE THREAD

**Issue by no5sunshine1029** [devblackops/Terminal-Icons#99]
when I open my powershell it show the warning, and Terminal-Icons not working.
I find out if I remove `Import-Module -Name Terminal-Icons` in `$PROFILE`, powershell will be OK, but Terminal-Icons didn't show. (It is successfully display yesterday, but now is not working)
Already use Nerd Font.
Uninstall Terminal-Icon and install it again still have the same problem
Here's the screen shot:
![image](https://user-images.githubusercontent.com/53609048/226531436-59b3d4f8-98b8-4712-a156-31b4c042cee6.png)

![image](https://user-images.githubusercontent.com/53609048/226531501-03262ef2-a7c0-4c3a-8afe-4f4daa8d8d21.png)

**Comment by no5sunshine1029** [comment]
I found the problem and fix it.
Just delete Terminal-Icons folder under `C:\Users\{Your user name}\AppData\Roaming\powershell\Community\`
and reinstall Terminal-Icons, restart powershell, module script will recreate the deleted folder, then the module can display normally.
![image](https://user-images.githubusercontent.com/53609048/226701615-2cc09f5a-df50-477c-87ca-812cc9b8937f.png)
I found the file location in Terminal-Icons.psm1's function: `Get-ThemeStoragePath`, and try the above solution, then it work for me.
![image](https://user-images.githubusercontent.com/53609048/226705007-c0fc63da-0be5-4d2e-8b92-c08f32bfea26.png)
Not sure where's the core bug is, so I can't explain it more

**Comment by epenflow** [comment]
thanks

**Comment by tvert** [comment]
Thanks @no5sunshine1029  - you tip about deleting (or renaming) tha roaming folder made the trik for me.
After re-installing the Terminal-Icons module I have compared the 'prefs.xml' file in that folder. The previous one was empty but the new one has a hastable serialized - I am putting the content of mine in case removing that folder is not enough:

<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
  <Obj RefId="0">
    <TN RefId="0">
      <T>System.Collections.Hashtable</T>
      <T>System.Object</T>
    </TN>
    <DCT>
      <En>
        <S N="Key">CurrentIconTheme</S>
        <S N="Value">devblackops</S>
      </En>
      <En>
        <S N="Key">CurrentColorTheme</S>
        <S N="Value">devblackops</S>
      </En>
    </DCT>
  </Obj>
</Objs>

**Comment by MarcosGil-404** [comment]
I changed the font to other who allows icons and it works.
